-- Teams schema for RisingNetwork (Clean Version)
-- Run in Supabase SQL editor

create extension if not exists "pgcrypto";

-- Drop existing tables to ensure clean setup
drop table if exists team_members cascade;
drop table if exists teams cascade;

-- Teams table
create table teams (
  id bigint primary key generated by default as identity,
  name text not null,
  college_id int references colleges(id) on delete cascade,
  created_by uuid references profiles(id) on delete cascade,
  max_members int not null default 5,
  created_at timestamptz not null default now()
);

-- Team members table with invitation system
create table team_members (
  id uuid primary key default gen_random_uuid(),
  team_id bigint references teams(id) on delete cascade,
  user_id uuid references profiles(id) on delete cascade,
  status text not null check (status in ('pending', 'accepted', 'declined')) default 'pending',
  invited_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (team_id, user_id)
);

-- Enable RLS
alter table teams enable row level security;
alter table team_members enable row level security;

-- Teams policies
create policy "Teams read"
  on teams for select
  using (
    exists (
      select 1
      from team_members tm
      where tm.team_id = teams.id
        and tm.user_id = auth.uid()
        and tm.status = 'accepted'
    )
  );

create policy "Teams insert"
  on teams for insert
  with check (
    auth.uid() = created_by
  );

create policy "Teams update"
  on teams for update
  using (
    auth.uid() = created_by
  );

-- Team members policies
create policy "Team members read"
  on team_members for select
  using (
    user_id = auth.uid()
    or (
      exists (
        select 1
        from team_members tm2
        where tm2.team_id = team_members.team_id
          and tm2.user_id = auth.uid()
          and tm2.status = 'accepted'
      )
    )
  );

create policy "Team members insert"
  on team_members for insert
  with check (
    -- Creator can add themselves as accepted
    (user_id = auth.uid() and status = 'accepted')
    -- Team members can invite connected users
    or (
      exists (
        select 1
        from team_members tm2
        where tm2.team_id = team_members.team_id
          and tm2.user_id = auth.uid()
          and tm2.status = 'accepted'
      )
      and status = 'pending'
      and invited_by = auth.uid()
    )
  );

create policy "Team members update"
  on team_members for update
  using (
    -- Users can update their own status (accept/decline invitations)
    user_id = auth.uid()
  )
  with check (
    -- Users can only change their own status
    user_id = auth.uid()
  );

-- Function to check if user is connected to another user
create or replace function is_connected(user_a uuid, user_b uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from connections
    where status = 'accepted'
      and (
        (requester_id = user_a and recipient_id = user_b)
        or (requester_id = user_b and recipient_id = user_a)
      )
  );
$$;

-- Function to check if user can invite another user to team
create or replace function can_invite_to_team(p_team_id bigint, p_inviter_id uuid, p_invitee_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select 
    -- Inviter must be an accepted team member
    exists (
      select 1
      from team_members tm
      where tm.team_id = p_team_id
        and tm.user_id = p_inviter_id
        and tm.status = 'accepted'
    )
    -- Users must be connected
    and is_connected(p_inviter_id, p_invitee_id)
    -- Invitee must not already be a member
    and not exists (
      select 1
      from team_members tm
      where tm.team_id = p_team_id
        and tm.user_id = p_invitee_id
    );
$$;

-- Updated function to check if user is team member
create or replace function is_team_member(p_team_id bigint, p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from team_members
    where team_id = p_team_id
      and user_id = p_user_id
      and status = 'accepted'
  );
$$;

-- Indexes for better performance
create index idx_teams_college_id on teams(college_id);
create index idx_teams_created_by on teams(created_by);
create index idx_team_members_team_id on team_members(team_id);
create index idx_team_members_user_id on team_members(user_id);
create index idx_team_members_status on team_members(status);

-- Trigger to update updated_at timestamp
create or replace function update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger update_team_members_updated_at
  before update on team_members
  for each row
  execute function update_updated_at_column();
